// ═══════════════════════════════════════════════════════
// NEW MINI — RESULTS VIEW
// Full results page — risk banner, charts, explanation
// ═══════════════════════════════════════════════════════


function ResultsView({ disease, result, userInputs, onBack, onReset }) {
  const config     = getDisease(disease);
  const formatted  = formatResult(result);
  const riskConfig = getRiskConfig(formatted.riskLevel);

  // Scroll to top on mount
  useEffect(() => {
    window.scrollTo({ top: 0, behavior: 'smooth' });
  }, []);

  return (
    <div className="results-view">
      <div className="results-inner">

        {/* ── HEADER ── */}
        <div className="results-header">
          <div className="results-title-wrap">
            <h1>
              {config.emoji} {config.name} Assessment
            </h1>
            <p>Based on your health parameters</p>
          </div>
          <div className="results-actions">
            <button className="btn-ghost" onClick={onBack}>
              ← Modify Inputs
            </button>
            <button className="btn-ghost" onClick={onReset}>
              ↺ New Prediction
            </button>
          </div>
        </div>

        {/* ── RISK BANNER ── */}
        <RiskBanner result={formatted} />

        {/* ── ANALYSIS SUMMARY ── */}
        <BestModelBadge result={formatted} />

        {/* ── CHARTS ROW ── */}
        <div className="charts-row">
          <RadarChart
            disease={disease}
            userInputs={userInputs}
          />
          <BarChart
            disease={disease}
            userInputs={userInputs}
          />
        </div>

        {/* ── EXPLANATION ── */}
        <Explanation
          result={formatted}
          disease={disease}
          userInputs={userInputs}
        />

        {/* ── RECOMMENDATIONS ── */}
        <RecommendationsCard riskLevel={formatted.riskLevel} disease={disease} />

        {/* ── DISCLAIMER ── */}
        <div className="results-disclaimer">
          <strong>Medical Disclaimer:</strong> This prediction is generated by machine
          learning models for informational purposes only. It is not a medical diagnosis.
          Please consult a qualified healthcare professional for proper evaluation and treatment.
        </div>

        {/* ── BOTTOM ACTIONS ── */}
        <div className="results-bottom-actions">
          <button className="btn-primary" onClick={onReset}>
            <span>↺ Start New Prediction</span>
          </button>
          <button className="btn-ghost" onClick={onBack}>
            ← Modify Parameters
          </button>
        </div>

      </div>
    </div>
  );
}

// ─── RECOMMENDATIONS CARD ─────────────────────────────
function RecommendationsCard({ riskLevel, disease }) {
  const allRecs = {
    low: [
      { icon: '🥗', title: 'Maintain Healthy Diet',   desc: 'Continue with balanced nutrition rich in fruits, vegetables and whole grains.' },
      { icon: '🏃', title: 'Regular Exercise',         desc: 'Keep up 150 minutes of moderate physical activity every week.' },
      { icon: '😴', title: 'Quality Sleep',            desc: 'Maintain 7 to 9 hours of restful sleep each night for optimal health.' },
      { icon: '🩺', title: 'Annual Checkup',           desc: 'Keep scheduling routine health checkups even when you feel well.' },
    ],
    moderate: [
      { icon: '👨‍⚕️', title: 'Schedule a Checkup',   desc: 'Visit your healthcare provider soon for a proper evaluation of your parameters.' },
      { icon: '🥗', title: 'Improve Your Diet',        desc: 'Reduce processed foods, sugar and sodium. Focus on whole and natural foods.' },
      { icon: '🏃', title: 'Increase Activity',        desc: 'Aim for at least 30 minutes of physical activity every day.' },
      { icon: '📋', title: 'Monitor Symptoms',         desc: 'Track any new or worsening symptoms and report them to your doctor promptly.' },
    ],
    high: [
      { icon: '🚨', title: 'Consult a Doctor Soon',    desc: 'Please schedule an appointment with a specialist as soon as possible.' },
      { icon: '💊', title: 'Review Medications',       desc: 'Discuss preventive treatments and medication options with your healthcare provider.' },
      { icon: '🔄', title: 'Lifestyle Changes',        desc: 'Make immediate changes to your diet, exercise routine and stress management.' },
      { icon: '📊', title: 'Regular Monitoring',       desc: 'Establish a routine health monitoring schedule with your medical team.' },
    ],
  };

  const diseaseRec = {
    heart:    { icon: '❤️',  title: 'Heart Health',    desc: 'Limit saturated fats, quit smoking and manage stress for better cardiovascular health.' },
    brain:    { icon: '🧠',  title: 'Brain Health',    desc: 'Control blood pressure, maintain healthy glucose and stay mentally active.' },
    kidney:   { icon: '🫘',  title: 'Kidney Care',     desc: 'Stay hydrated, control blood pressure, limit sodium and avoid overuse of painkillers.' },
    diabetes: { icon: '🩸',  title: 'Blood Sugar',     desc: 'Monitor glucose regularly, reduce carbs and maintain a healthy body weight.' },
  };

  const recs = [diseaseRec[disease], ...allRecs[riskLevel]];

  return (
    <div
      className="explanation-card"
      style={{ animationDelay: '0.6s' }}
    >
      <div className="explanation-header">
        <div className="explanation-icon">💡</div>
        <div className="explanation-title">Personalized Recommendations</div>
      </div>

      <div style={{
        display: 'grid',
        gridTemplateColumns: 'repeat(2, 1fr)',
        gap: '12px',
      }}>
        {recs.map((rec, i) => (
          <div
            key={i}
            style={{
              display: 'flex',
              gap: '12px',
              padding: '14px',
              background: 'rgba(255,255,255,0.02)',
              border: '1px solid var(--glass-border)',
              borderRadius: 'var(--radius-md)',
              transition: 'all 0.3s var(--ease-smooth)',
              cursor: 'default',
              opacity: 0,
              animation: `slide-up 0.4s var(--ease-out) ${0.6 + i * 0.08}s forwards`,
            }}
            onMouseEnter={e => {
              e.currentTarget.style.background = 'rgba(255,255,255,0.04)';
              e.currentTarget.style.borderColor = 'var(--border-light)';
            }}
            onMouseLeave={e => {
              e.currentTarget.style.background = 'rgba(255,255,255,0.02)';
              e.currentTarget.style.borderColor = 'var(--glass-border)';
            }}
          >
            <div style={{
              width: '40px',
              height: '40px',
              borderRadius: '12px',
              background: 'var(--teal-glow)',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              fontSize: '20px',
              flexShrink: 0,
            }}>
              {rec.icon}
            </div>
            <div>
              <div style={{
                fontSize: '14px',
                fontWeight: '600',
                color: 'var(--text)',
                marginBottom: '4px',
                fontFamily: 'var(--font-display)',
              }}>
                {rec.title}
              </div>
              <div style={{
                fontSize: '12px',
                color: 'var(--text-muted)',
                lineHeight: '1.5',
              }}>
                {rec.desc}
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}